=== babikovasofi/BabikovaPIN252t/iphones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="iphone_sales" type="IphoneSalesType"/>

  <xs:complexType name="IphoneSalesType">
    <xs:sequence>
      <xs:element name="analytics" type="AnalyticsType"/>
      <xs:element name="iphone_models" type="IphoneModelsType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AnalyticsType">
    <xs:sequence>
      <xs:element name="period" type="xs:string"/>
      <xs:element name="total_models" type="xs:integer"/>
      <xs:element name="methodology" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="source" type="xs:string" use="required"/>
    <xs:attribute name="year" type="xs:integer" use="required"/>
  </xs:complexType>

  <xs:complexType name="IphoneModelsType">
    <xs:sequence>
      <xs:element name="model" type="ModelType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="category" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="ModelType">
    <xs:sequence>
      <xs:element name="specifications" type="SpecificationsType"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="SpecificationsType">
    <xs:sequence>
      <xs:element name="image" type="xs:string"/>
      <xs:element name="release_year" type="xs:integer"/>
      <xs:element name="display" type="xs:string"/>
      <xs:element name="sales" type="xs:integer"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== babikovasofi/BabikovaPIN252t/iphones.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="iphones.xsl"?>
<iphone_sales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="iphones.xsd">

  <analytics source="Statista" year="2024">
    <period>2014-2024</period>
    <total_models>5</total_models>
    <methodology>Анализ данных международных аналитических агентств</methodology>
  </analytics>

  <iphone_models category="top_sellers">

    <model name="iPhone 6">
      <specifications>
        <image>image/6 iphone.jpg</image>
        <release_year>2014</release_year>
        <display>4.7"</display>
        <sales>220</sales>
      </specifications>
    </model>

    <model name="iPhone 11">
      <specifications>
        <image>image/11 iphone.jpg</image>
        <release_year>2019</release_year>
        <display>6.1"</display>
        <sales>170</sales>
      </specifications>
    </model>

    <model name="iPhone 12">
      <specifications>
        <image>image/12 iphone.jpg</image>
        <release_year>2020</release_year>
        <display>6.1"</display>
        <sales>150</sales>
      </specifications>
    </model>

    <model name="iPhone 13">
      <specifications>
        <image>image/13 iphone .jpg</image>
        <release_year>2021</release_year>
        <display>6.1"</display>
        <sales>140</sales>
      </specifications>
    </model>

    <model name="iPhone 15">
      <specifications>
        <image>image/15 iphone.jpg</image>
        <release_year>2023</release_year>
        <display>6.1"</display>
        <sales>80</sales>
      </specifications>
    </model>

  </iphone_models>

</iphone_sales>
